### ISSUE TITLE
Can't capture screen on Ubuntu when large text is turned on: "Non-integer value" error

### ISSUE THREAD

**Issue by tcg96** [MagicCap/MagicCap#171]
I am using Ubuntu 18.04 with the "Large Text" accessibility setting turned on because original text is quite small on my laptop's screen.

When starting to take a screen capture, MagicCap dims and zooms the screen a little bit instead of just dimming, so the whole screen cannot be seen.
After dragging what I want to capture, it gives an error saying "Non-integer value for left of" and then a number with a lot of decimal places. (Sometimes it says "right" or "top" instead of "left", and the number changes depending where I tried to take the screen shot.) No image is saved or uploaded.

![Screenshot from 2019-06-19 23-59-27](https://user-images.githubusercontent.com/22633459/59804888-e9459000-92ef-11e9-9f37-05eb54904f51.png)
This is an example error message (taken with the built-in Ubuntu screen shot tool).

I tried both the latest stable and pre-release versions of MagicCap (1.0.3 and 1.1.0b4), they give the same error when large text is turned on in the OS's settings. The program works perfectly when large text is turned off.

**Comment by JakeMakesStuff** [comment]
Hi and thanks for the bug report. I’m just about to go to sleep (it’s 23:35 where I am atm), but I will take a look in the morning.

**Comment by JakeMakesStuff** [comment]
Should be fixed in the next beta. 👍

**Comment by tcg96** [comment]
Thanks for fixing this. Now screen shots work, but there's still a problem: it still zooms the screen a little bit, so I cannot capture beyond a certain area. My screen resolution is 1920*1080 and I can only capture a 1475*830 area from the top left corner. Again, this problem is not present when Large Text is turned off.

![Screenshot from 2019-06-23 19-15-05](https://user-images.githubusercontent.com/22633459/59979697-450f6200-95eb-11e9-9f80-6d405adc3dc0.png)
This is what the whole screen looks like when I select "Screen Capture". It is not supposed to zoom in like that.

**Comment by JakeMakesStuff** [comment]
https://github.com/MagicCap/MagicCap/releases/tag/v2.0.0b2 should actually fix this now hopefully.

**Comment by tcg96** [comment]
It seems to work fine now!
